name: Pull Request

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pull Requests check
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Run detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - run: echo "Build status=${{ job.status }}."
